// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('1', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('1', async function() {
    await driver.get("https://bstackdemo.com/")
    await driver.manage().window().setRect({ width: 1050, height: 562 })
    await driver.findElement(By.id("signin")).click()
    {
      const element = await driver.findElement(By.css(".css-1pahdxg-control > .css-1hwfws3"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.id("react-select-2-option-0-3"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.id("username")).click()
    await driver.findElement(By.id("react-select-2-input")).sendKeys("demouser")
    await driver.findElement(By.css(".Modal_modal__3I0HK")).click()
    {
      const element = await driver.findElement(By.css(".css-1pahdxg-control .css-1wa3eu0-placeholder"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.css("#react-select-2-group-0-heading span:nth-child(1)"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.id("username")).click()
    await driver.findElement(By.id("react-select-2-input")).sendKeys("demouser")
    await driver.findElement(By.id("react-select-2-input")).sendKeys(Key.ENTER)
    await driver.findElement(By.css(".css-1wa3eu0-placeholder")).click()
    await driver.findElement(By.id("react-select-3-input")).sendKeys("testingisfun99")
    await driver.findElement(By.id("react-select-3-input")).sendKeys(Key.ENTER)
    await driver.findElement(By.id("login-btn")).click()
    {
      const element = await driver.findElement(By.id("login-btn"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
  })
})
